"""add user_id

Revision ID: d3fa94c2dea8
Revises: 65db35e5435e
Create Date: 2024-12-13 15:51:49.727013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3fa94c2dea8'
down_revision: Union[str, None] = '65db35e5435e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadiums', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('stadiums_owner_id_fkey', 'stadiums', type_='foreignkey')
    op.create_foreign_key(None, 'stadiums', 'user', ['user_id'], ['id'])
    op.drop_column('stadiums', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadiums', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stadiums', type_='foreignkey')
    op.create_foreign_key('stadiums_owner_id_fkey', 'stadiums', 'user', ['owner_id'], ['id'])
    op.drop_column('stadiums', 'user_id')
    # ### end Alembic commands ###
